In [29]:
import numpy as np
import pandas as pd

In [96]:
N = 1 # Number of Episodes

M = 1 # number of actions to perform in each episode

Q_Matrix = {} # (state, actions):Q_Value

epsilon = 0.1 # Can start with high ε, and decrease it over the run
eta = 0.2
gamma = 0.9

# five “sensors”: Current, North, South, East, and West
# Values : Empty, Can, and Wall
# five possible actions: Move-North, Move-South, Move-East, Move-West, and Pick-Up-Can
# reward of 10 for picking up can, -5 crashing into wall 
# and -1 if he tries to pick up a can in an empty square.

# Q(s,a)next = Q(s,a)current + η (reward + γ max(a´) Q(s´,a´) – Q(s, a)current)


def initial_state():
            '''
            # random 10x10 grid
            # Each square has 1/2 probability to contain a can '1'
            # Robby is placed in a random square
            '''
            grid = np.random.binomial(1, p=.5, size=(10,10))
            robby = [np.random.choice(np.arange(10)), np.random.choice(np.arange(10))]
            return (grid, robby)

    


# def Q_Learning(s_t, North, East, South, West, Q_Matrix, grid):
#     best_score = -100
#     alpha = 0.2
#     gamma = 0.9
#     Q_current = Q_Matrix[(s_t,North)]

#             # pickup_can, North, East, South, West = possible_actions(North, s_t)
#     max_Q,action = max_Q(s_t, North, grid, Q_Matrix)

#             Q_next = Q_current + alpha * (grid[North] + gamma*(children)   )



#             if(score > best_score):
#                 score == best_score
#         if(best_score == -100):

#     if(action == False):
#         return (-1)

# # def greedy_action_selection(robby, s_t, grid, Q_Matrix):
# def max_action():

def max_Q(sensors, Q_Matrix, robby):
    print(robby)
    
    best_Q = 0
    for i,a in enumerate(sensors):
        key = tuple(robby) + tuple(str(a))
        if(key in Q_Matrix):
            Q = Q_Matrix[key]
            if(Q > best_Q):
                best_Q = Q
                action = a
    if(best_Q == 0):
        action = 'N'

    return (action)

def epsilon_greedy(epsilon, sensors, grid, robby, Q_Matrix):
    a =['C', 'N', 'E', 'S', 'W']
    # With probability (1 − ε)  choose action that maximizes current Q(s,a)
    # With probability ε choose random action
    prob_random = epsilon * 1000
    chance = np.random.randint(0, 1000) # Inclusive to exclusive
    print(f"The chance is: {chance}")
    if(chance >=prob_random):
        print("max Action")
        action = max_Q(sensors, Q_Matrix, robby)
    if(chance < prob_random):
        print("random action")
        chance = np.random.randint(0, 5) 
        action = str(a[chance])

    return(action)

def possible_actions(grid, robby):
    # 0 empty cell, 1 is can, 2 is wall
    sensors = {}
    x = robby[0]
    y = robby[1]
    score = grid[robby[0], robby[1]] # robby's current state
    if(score == 1):
        sensors['C'] = 1
    if(score!= 1):
        sensors['C'] = 0

    # Move-North
    North = (x,y+1)
    if(North[1] == 10):
        sensors['N'] = 2
    if(North[1] != 10):
        if(grid[North[0]][North[1]] == 1):
            sensors['N'] = 1
        if(grid[North[0]][North[1]] == 0):
            sensors['N'] = 0

    # Move-East
    East = (x+1,y)
    if(East[0] == 10):
        sensors['E'] = 2
    if(East[0] != 10):
        if(grid[East[0]][East[1]] == 1):
            sensors['E'] = 1
        if(grid[East[0]][East[1]] == 0):
            sensors['E'] = 0

    # Move-South
    South = (x,y-1)
    if(South[1] == -1):
        sensors['S'] = 2
    if(South[1] != -1):
        if(grid[South[0]][South[1]] == 1):
            sensors['S'] = 1
        if(grid[South[0]][South[1]] == 0):
            sensors['S'] = 0
        
    # Move-West
    West = (x-1,y)
    if(West[0] == -1):
        sensors['W'] = 2
    if(West[0] != -1):
        if(grid[West[0]][West[1]] == 1):
            sensors['W'] = 1
        if(grid[West[0]][West[1]] == 0):
            sensors['W'] = 0
    return(sensors)


def next_state(action, grid, current):
    x = current[0]
    y = current[1]
    if(action == 'C'):
        return(current)
    if(action == 'N'):
        return grid[x][y+1]
    if(action == 'E'):
        return grid[x+1][y]
    if(action == 'S'):
        return grid[x][y-1]
    if(action == 'W'):
        return grid[x-1][y]

def next_state_and_reward(a_t, sensors, grid, current):
    # {'C': 1, 'N': 0, 'E': 0, 'S': 1, 'W': 0}
    if(sensors[a_t] == 0):
        print("Proceed")
        print('0 Reward')
        S_t_next = next_state(action, grid, current)
        reward = 0
    if(sensors[a_t] == 1):
        print("Proceed")
        print('10 Reward, pick up can')
        S_t_next = next_state(action, grid, current)
        grid[current]= 0
        reward = 10

    if(sensors[a_t] == 2):
        S_t_next = current
        print("Wall")
        reward = -5
    return (S_t_next, reward, grid)

for episode in range(N):
    grid, robby = initial_state()
    current_state = robby
    a_t = 'C' # initial state
    for action in range(M):
        print(current_state)
        print(print(grid[::-1,:])) # display 0,0 at bottom left
        sensors = possible_actions(grid, current_state)
        print(sensors)
        
        # current Q
        key = tuple(current_state) + tuple(a_t)
        if(key in Q_Matrix):
            current_Q = Q_Matrix[key]
        if(key not in Q_Matrix):
            current_Q = 0
            print(current_state)
            # key = tuple(current_state) + tuple(a_t) 
            Q_Matrix[key] = 0

        a_t = epsilon_greedy(epsilon, sensors, grid, current_state, Q_Matrix)

        print(a_t)
        S_t_next, reward, grid = next_state_and_reward(a_t, sensors, grid, current_state)

        key2 = tuple(S_t_next) + tuple(a_t)
        update = tuple(current_state) + tuple(a_t)
        if(key in Q_Matrix): 
            next_Q = Q_Matrix[update]
        if(key not in Q_Matrix):
            next_Q = 0
        
        update_Q = current_Q + (eta * (reward + (gamma * next_Q) - current_Q) )

        Q_Matrix[update] = update_Q

        current_state = S_t_next
            
    
# epsilon = 0.1 # Can start with high ε, and decrease it over the run
# eta = 0.2
# gamma = 0.9




# ex. test N = 5,000 ; M = 200 ; 𝜂= 0.2; 𝛾= 0.9

[6, 7]
[[0 1 0 0 1 0 1 0 0 0]
 [0 0 1 0 1 0 1 0 0 0]
 [1 1 1 1 0 0 1 0 1 0]
 [0 0 0 1 0 0 0 1 0 0]
 [1 1 0 0 1 0 0 1 1 0]
 [1 0 1 1 0 0 0 1 0 1]
 [1 1 0 1 0 1 1 1 1 1]
 [0 0 1 0 0 1 0 1 0 0]
 [1 1 1 1 0 1 1 1 1 1]
 [1 1 0 1 0 1 0 1 1 1]]
None
{'C': 1, 'N': 0, 'E': 0, 'S': 0, 'W': 1}
[6, 7]
The chance is: 16
random action
W
Proceed
10 Reward, pick up can


TypeError: unhashable type: 'list'

In [87]:
d = {}
a = [3, 4]

b = 'N'
key = tuple(a) + tuple(b)

d[key] = 4

print(d)

{(3, 4, 'N'): 4}
